### ISSUE TITLE
Magic parameter mechanism for embedding text

### ISSUE THREAD

**Issue by simonw** [datasette/datasette-embeddings#14]
To help us build SQL interfaces that embed text and then pass the result to the model.

Using this new feature in Datasette core:
- https://github.com/simonw/datasette/issues/2441

**Comment by simonw** [comment]
Put this in a `queries.yml` file:
```yaml
databases:
  content:
    queries:
      embed:
        select :_openaiembeddefault_q
```
And then:
```bash
datasette content.db -c queries.yml -p 8003 -s plugins.datasette-embeddings.api_key "$(jq -r '.openai' "$(dirname "$(llm logs path)")/keys.json")"
````
And now: http://127.0.0.1:8003/content/embed?q=hello

![CleanShot 2024-11-15 at 13 30 05@2x](https://github.com/user-attachments/assets/8d5079a6-d8e1-4d17-98a5-e62b41233c87)
